name: Auto Scraping

on:
  schedule:
    # S'exécute tous les lundis à 7h00 UTC
    - cron: "0 7 * * mon"
  workflow_dispatch: # Permet de lancer le script manuellement pour tester

jobs:
  report:
    runs-on: ubuntu-latest
    environment: scraper

    env:
      SUPABASE_URL: ${{ secrets.API_URL }}
      SUPABASE_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pandas supabase requests beautifulsoup4 lxml

      - name: Exécution du script
        run: python script.py