name: Auto Scraping

on:
  schedule:
     - cron: "0 7 * * mon"
     - cron: "0 19 * * thu" 
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    environment: scraper

    env:
      SUPABASE_URL: ${{ secrets.API_URL }}
      SUPABASE_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pandas supabase requests beautifulsoup4 lxml

      - name: Exécution du script
        run: python script.py